google/periph

experimental/conn/onewire/crc_test.go, experimental/conn/onewire/onewire.go, experimental/conn/onewire/onewire_test.go
Make Register() slightly more resilient.
=> onewire: Increase unit test coverage

CONTRIBUTORS, conn/spi/spismoketest/spismoketest.go, devices/lepton/lepton.go, host/bcm283x/gpio.go, host/chip/chip.go, host/distro/distro.go, host/rpi/rpi.go, host/sysfs/spi.go
Hi, these are some simplifications suggested by [gosimple](https://github.com/dominikh/go-simple).
Best.
=> Simplifying code

conn/conn.go, conn/conn_test.go, conn/doc.go
Explains the 'Bus → Port → Conn' concept that I had failed to put into words up to now
No code change.
=> conn: Improve documentation

conn/gpio/gpioreg/gpioreg.go, conn/gpio/gpioreg/gpioreg_test.go, conn/pin/pinreg/pinreg.go
I was advertizing this functionality but forgot to implement it. 😱
=> pinreg: automatically register gpio.PinIO to gpioreg

CONTRIBUTORS, host/bcm283x/clock.go, host/bcm283x/gpio.go, host/bcm283x/pwm.go
- Use fix 250MHz clock
- Set PWM registers correctly.
=> Make hardware PWM work.

devices/bmxx80/bmp180.go, devices/bmxx80/bmp180_test.go, devices/bmxx80/bmxx80.go, devices/ds18b20/ds18b20.go, devices/ds18b20/ds18b20_test.go, devices/ds248x/dev.go, devices/ds248x/ds248x_test.go, devices/lepton/cci/cci.go, devices/lepton/cci/cci_test.go, devices/tm1637/tm1637.go, devices/tm1637/tm1637_test.go
It slows down tests, nobody wants that.
=> Remove all time.Sleep calls during tests

AUTHORS, CONTRIBUTORS
Including myself as contributor as suggested in #213 .
=> add new contributor

cmd/onewire-list/main.go
I created a simple and generic onewire device listing command. I found it helpful to test host implementations.
=> onewire-list command added

experimental/devices/mfrc522/commands/registers.go, experimental/devices/mfrc522/mfrc522.go
Catch errors
Update formatting
Signed-off-by: Eugene Dzhurinsky <jdevelop@gmail.com>
=> MFRC522: Code review follow-up

experimental/host/beagle/beagle.go, experimental/host/beagle/beagle_other.go, experimental/host/beagle/black/black.go, experimental/host/beagle/black/black_arm.go, experimental/host/beagle/black/black_other.go
=> add support for the BeagleBone black

conn/gpio/gpiotest/gpiotest.go
Let me know if there is more to do.
=> enhance logging wrappers

experimental/cmd/cap1xxx/main.go, experimental/devices/cap1xxx/cap1xxx.go, experimental/devices/cap1xxx/cap1xxx_go1_8_test.go, experimental/devices/cap1xxx/cap1xxx_options.go, experimental/devices/cap1xxx/cap1xxx_test.go, experimental/devices/cap1xxx/example_test.go
cap1166 can be found in Display-O-Tron HAT by Pimoroni.
=> cap1xxx: generalize cap1188 to support more devices

devices/apa102/apa102_test.go
Pulling these out of https://github.com/google/periph/pull/254 per review comment.
=> apa102: add new benchmarks for raster refactor

devices/apa102/apa102.go, devices/apa102/apa102_test.go
This adds a new option to bypass the perceptual remapping code and
directly write the RGB values to the APA102, similar to what the
AdaFruit DotStar Python library does.
=> apa102: Add RawColors option

host/bcm283x/gpio.go
Computation of PWM resolution had desired and base frequencies reversed.
=> Corrected a typo in the bcm283x PWM implementation.

experimental/devices/bitbang/spi.go
=> bitbang/spi: move pin init to Connect() from NewSPI()

cmd/ssd1306/main.go, devices/ssd1306/ssd1306.go, devices/ssd1306/ssd1306_test.go
=> ssd1306: add options to customize the hardware pin layout

experimental/devices/mfrc522/mfrc522.go
+ Antenna Gain
* Terminating Wait if Halt received
* Renamed SetOperationtimeout to SetOperationTimeout
=> A few changes for mfrc522

experimental/cmd/as7262/main.go, experimental/devices/as7262/as7262.go, experimental/devices/as7262/as7262_test.go, experimental/devices/as7262/example_test.go, experimental/devices/as7262/testdata_test.go
Refactor to remove context.Context
=> as7262: Remove requirement for go1.7

experimental/cmd/hx711/main.go, experimental/devices/hx711/hx711.go
- Remove ReadAveraged - it's not a good fit here.
- Use the proper datasheet URL.
- Remove some constants.
- Rename StopContinuousRead to Halt.
=> hx711: tidy up a few remaining PR comments

conn/physic/units.go, conn/physic/units_test.go
Add option for no original string.
=> physic: Change parseError.Error() formatting

experimental/devices/ads1x15/ads1x15.go
No functional change.
- Move private globals at the bottom of the file.
- Move ads1x15AnalogPin close to its methods.
- Stop using named return variable.
- Inline newADS1x15.
- Move gainConfig and gainVoltage as global variables.
- Wraps comments.
- Rename mutex to mu.
- Use -math.MaxInt16 instead of math.MinInt16 because of the voltage multiplier.
- Change error strings to start with a lower case.
=> ads1x15: style improvement

conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
Enable physic.Frequency to use the flag.Value interface.
=> physic: Add flag.Value implementation for Frequency 

experimental/devices/ina219/doc.go, experimental/devices/ina219/ina219.go, experimental/devices/ina219/ina219_go1_7_test.go
currentLSB is supposed to be Maximum Expected Current / 2^15
2 << 15 is 2 ^ 16, not 2 ^ 15.
=> Fix currentLSB calculation in ina219

conn/physic/doc.go, conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
Add Set().
Add tests.
Add SI Units to docs.
Add Examples.
=> physic: Add flag.Value implementation for ElectricResistance

conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
Continuation of #303 adding more units that implement the flag.Value interface.
Add ElectricCurrent 
Add Pressure
Add Power
Add Energy
Add ElectricalCapacitance
Add LuminousIntensity
Add LuminousFlux
=> physic: flag.Value interface for various units.

experimental/cmd/hx711/main.go, experimental/devices/hx711/hx711.go, experimental/devices/hx711/hx711_test.go
=> hx711: implement analog.PinADC

conn/gpio/example_test.go
=> gpio: fix pwm example to make it visible in godoc

experimental/cmd/sn3218/main.go, experimental/devices/sn3218/doc.go, experimental/devices/sn3218/example_test.go, experimental/devices/sn3218/sn3218.go, experimental/devices/sn3218/sn3218_test.go
Add experimental device for SN3218 LED driver.
=> sn3218 - add experimental support for sn3218 LED driver

host/fs/fs_linux.go, host/fs/fs_linux_test.go
It has a String(), which is useful when debugging. It will be used more
later.
=> fs: add epollEvent type

cmd/periph-smoketest/gpiosmoketest/gpiosmoketest.go
- Use different sleep delay when an edge is expected or unexpected.
- Coding style tweaks.
- Improve comments.
- Improve WaitForEdge() handling, log at the right place.
- Add test case to be enabled once #323 is fixed.
=> gpiosmoketest: improvements before improving gpio edge handling

host/fs/fs_linux_test.go
=> fs: workaround a test case that is flaky

experimental/cmd/ccs811/main.go, experimental/devices/ccs811/ccs811.go, experimental/devices/ccs811/ccs811_test.go, experimental/devices/ccs811/doc.go
Notes
Please prefix the issue title with the primary package affected. For example, if
this PR fixes periph.io/x/periph/host/sysfs, prefix the PR title with "sysfs:".
Please add new drivers under "experimental". Wonder what it takes to promote a
driver as "stable"? See https://periph.io/project/#driver-lifetime-management
A stable driver requires the smallest API surface, good unit test code coverage,
good documentation and a page in
https://github.com/periph/website/tree/master/site/content/device so it can show
up at https://periph.io/device.
Mention the issue number it fixes or add the details of the changes if it
doesn't have a specific issue.
Examples:
Fixes #12345
Helps with #12345 but doesn't not completely fix it.
=> experimental: new device driver - CCS811

conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
These are commonly needed and trickier to use.
Update examples accordingly.
=> physic: add Temperature.Celsius() and Fahrenheit()

experimental/devices/inky/inky.go
=> experimental: Add more error checking for inky

host/fs/fs_linux.go, host/fs/fs_linux_test.go
Remove the lock from wakeUpLoop(). I suspect it is what was deadlocking
on travis.
Remove the tear down code. It was hard to make tear down never deadlock in unit
tests, so leak the goroutine instead.
Properly release the lock on initialization failure.
Make follow up init() call to be lockless.
=> fs: try to fix a deadlock in the new code

host/sysfs/gpio.go
It seems that trying to export a GPIO when it's already exported may
fail on a BeagleBone. Try to open the GPIO if it is present, instead of
always trying to export.
Redo the error management when opening a pin.
=> sysfs: work in the case where export fails when already exported

experimental/devices/pca9685/pca9685.go
The PCA9685's datasheet is available [here](https://cdn-shop.adafruit.com/datasheets/PCA9685.pdf).
First commit cleanups some stuff you commented on in https://github.com/google/periph/pull/296.
Second commit makes use of the auto-increment capability of the device to simplify contiguous writes. You've talked about `mmr`, do you think it's still required?
I tested it with a couple of servos. Do you have plans for the [servo module](https://github.com/google/periph/blob/master/experimental/devices/pca9685/servo.go)? I feel like one should be able to associate some `Servo`s to different `ServoGroup`s and the channel should be abstracted away (for example it could be possible to set the angle of all the `Servo`s in the `ServoGroup`).
=> pca9685: cleanup

host/bcm283x/dma.go
The DMA controlBlocks are unrolled and the parameter txLen is set to a fixed value.
=> bcm283x: Fixes #226: unrolling DMA controlBlocks

host/bcm283x/dma.go
Constants refactoring (fixed comment on last PR and replaced the "4" by a constant)
Added documentation about the DMA channel.
Thanks!
=> bcm283x: Follow-up on #440: Updated DMA documentation

host/bcm283x/gpio.go, host/bcm283x/gpio_test.go
=> bcm283x:Add support for internal pull resistor used in BCM2711
