cmd/bme280/main.go, cmd/i2c-list/main.go, cmd/i2c/main.go, cmd/ssd1306/main.go, conn/gpio/gpio.go, conn/i2c/i2c.go, conn/i2c/i2c_test.go, conn/i2c/i2csmoketest/i2csmoketest.go, conn/i2c/i2ctest/i2ctest.go, conn/i2c/i2ctest/i2ctest_test.go, conn/onewire/onewiresmoketest/onewiresmoketest.go, conn/reg/reg_test.go, devices/bme280/bme280_test.go, devices/ds248x/ds248x_test.go, devices/ssd1306/ssd1306_test.go, experimental/driverskeleton/driverskeleton_test.go, host/sysfs/i2c.go
This is a breaking change.
This is closer to how gpio behaves yet different in practice because of the
different challenges.
spi will be updated later to behave the same. Add support for aliases, which is
very useful, and it permits the CLI tools to accept a free form string to
specify the bus name.
- Increase test coverage of i2c and i2ctest to 100%.
- Add i2c.Pins implementation to i2ctest.Playback.
=> i2c: convert from "number only" to named buses plus aliases

cmd/apa102/main.go, cmd/bme280/main.go, cmd/spi-list/main.go, cmd/ssd1306/main.go, conn/spi/spi.go, conn/spi/spi_test.go, conn/spi/spismoketest/spismoketest.go, conn/spi/spitest/spitest.go, conn/spi/spitest/spitest_test.go, devices/apa102/apa102_test.go, host/sysfs/i2c.go, host/sysfs/spi.go
Because of the way the SPI bus is exposed via sysfs, do not use the same pattern
as i2c. This may change as more OSes are supported.
Increase test coverage for spi and spitest to 100%.
=> spi: Rewrite similar to how i2c was refactored

conn/spi/spi.go, conn/spi/spireg/spireg_test.go, conn/spi/spismoketest/spismoketest.go, conn/spi/spitest/spitest.go, conn/spi/spitest/spitest_test.go, devices/apa102/apa102.go, devices/apa102/apa102_test.go, devices/bme280/bme280.go, devices/ssd1306/ssd1306.go, experimental/devices/bitbang/spi.go, host/sysfs/spi.go
- Allow both app and device drive set max bus speed.
- Make DevParams callable only exactly once.
- sysfs: make SPI implement io.Reader.
=> spi: Update spi.Conn to separate app and device configuration.

cmd/push.sh
Go binaries are highly compressible. This greatly speeds transfers on slow networks.
=> rsync compress

devices/bme280/bme280.go
i like the idea for the newCalibration func in the bmp180 driver.
it should be done for the bme too.
another point that could be adressed is in bme280_test.go.
we could reuse the newCalibration func for the real extracted data.
what do you think?
=> use a newCalibration func like in bmp180

cmd/spi-io/main.go, conn/spi/spi.go, conn/spi/spireg/spireg.go, conn/spi/spireg/spireg_test.go, conn/spi/spismoketest/spismoketest.go, conn/spi/spitest/spitest.go, conn/spi/spitest/spitest_test.go, devices/apa102/apa102.go, devices/apa102/apa102_test.go, devices/bme280/bme280.go, devices/bme280/bme280_test.go, devices/bme280/bme280smoketest/bme280smoketest.go, devices/lepton/lepton.go, devices/lepton/lepton_test.go, devices/ssd1306/ssd1306.go, devices/ssd1306/ssd1306_test.go, devices/ssd1306/ssd1306smoketest/ssd1306smoketest.go, host/sysfs/spi.go, host/sysfs/spi_test.go
This clarifies the difference on ownership and makes it clear that DevParams()
is essentially a 'connection factory'.
Doing this caught inconsistencies in the unit tests. Made the structs in spitest
enforce the fact that DevParams() can only be called once.
=> spi: Refactor Conn and ConnCloser into Conn, Port and PortCloser

AUTHORS, CONTRIBUTORS, host/rpi/rpi.go
I needed to add support for the Raspberry Pi Zero W. I thought it would be wiser to specify revisions explicitly and I found a table [here](http://elinux.org/RPi_HardwareHistory) with an exhaustive list.
=> Set version of RPi for all known revisions

cmd/README.md, cmd/apa102/main.go, cmd/bme280/main.go, cmd/lepton/main.go, cmd/periph-info/README.md, cmd/spi-io/main.go, cmd/spi-list/main.go, cmd/ssd1306/main.go, conn/i2c/i2csmoketest/i2csmoketest.go, conn/spi/spi.go, conn/spi/spireg/spireg.go, conn/spi/spireg/spireg_test.go, conn/spi/spismoketest/README.md, conn/spi/spismoketest/spismoketest.go, conn/spi/spitest/spitest.go, conn/spi/spitest/spitest_test.go, devices/apa102/apa102.go, devices/apa102/apa102_test.go, devices/apa102/doc.go, devices/bme280/bme280_test.go, devices/bme280/bme280smoketest/bme280smoketest.go, devices/lepton/lepton_test.go, devices/ssd1306/ssd1306.go, devices/ssd1306/ssd1306_test.go, devices/ssd1306/ssd1306smoketest/ssd1306smoketest.go, experimental/cmd/bmp180/main.go, experimental/devices/bitbang/spi.go, host/sysfs/spi.go, host/sysfs/spi_test.go
As people like to copy paste code, make sure that the semantic of the variable
names is always relevant w.r.t. the object they refer to. In particular, do not
use 'bus' to refer to an spi.Port or spi.PortCloser, as this is blur the
distinction.
Also rename a few fooName to fooID.
=> spi: rename variables 'bus' to 'port' where applicable

host/sysfs/gpio.go
The sysfs Pin.open function checked for the pin already being exported, but left p.err set when this happened. Only set the p.err once we've determined that it's a real error.
=> Don't error out when opening an already exported sysfs GPIO pin.

host/allwinner/dma.go, host/allwinner/gpio.go, host/allwinner/gpio_pl.go, host/bcm283x/dma.go, host/bcm283x/dma_test.go, host/bcm283x/gpio.go, host/pmem/alloc.go, host/pmem/doc.go, host/pmem/view.go, host/pmem/view_test.go
- bcm283x: Migrate 'smokeTest' struct size check to unit test.
- pmem: Improve package documentation.
- pmem: Remove the need from callers to use reflect.ValueOf().
- pmem: Add support to map a slice which calculate the len/cap automatically.
- pmem: Rename Struct() to AsPOD().
- pmem: Add AsPOD() support for native POD (plain old data) types like uint8,
float64, etc.
- pmem: Add AsPOD() support for array of POD.
- pmem: Make AsPOD() check for struct much stricter.
=> pmem: rename Struct to AsPOD; add support for slice and array

periph.go
And update a stale reference to DESIGN.md which now is on the official web site
The new layout is easier to read in godoc.
=> periph: Improve the package doc

cmd/spi-io/main.go, conn/spi/spi.go, conn/spi/spireg/spireg_test.go, conn/spi/spismoketest/spismoketest.go, conn/spi/spitest/spitest.go, conn/spi/spitest/spitest_test.go, devices/apa102/apa102.go, devices/apa102/apa102_test.go, devices/bme280/bme280.go, devices/bme280/bme280_test.go, devices/lepton/lepton.go, devices/lepton/lepton_test.go, devices/ssd1306/ssd1306.go, devices/ssd1306/ssd1306_test.go, experimental/devices/bitbang/spi.go, host/sysfs/spi.go, host/sysfs/spi_test.go
It better conveys the purpose of the function, which is to create a Conn over a
Port.
This should be the last breaking change before v2.0.0 release.
=> spi: Rename Port.DevParams to Connect

cmd/bme280/main.go, conn/i2c/i2ctest/i2ctest.go, conn/mmr/mmr.go, conn/mmr/mmr_test.go, devices/apa102/apa102.go, devices/bme280/bme280.go, devices/bme280/bme280_test.go, devices/bme280/bme280smoketest/bme280smoketest.go, devices/devices.go, devices/devicestest/display.go, devices/ds18b20/ds18b20.go, devices/ds248x/dev.go, devices/lepton/cci/cci.go, devices/lepton/cci/cci_test.go, devices/lepton/lepton.go, devices/lepton/lepton_test.go, devices/lirc/lirc.go, devices/ssd1306/ssd1306.go, devices/tm1637/tm1637.go, experimental/devices/bitbang/i2c.go, experimental/devices/bitbang/spi.go, experimental/devices/bmp180/bmp180.go, host/sysfs/gpio.go, host/sysfs/i2c.go, host/sysfs/led.go, host/sysfs/spi.go, host/sysfs/thermal_sensor.go, host/sysfs/thermal_sensor_test.go
- Unexport the Standby parameter.
- Have SenseContinuous accept time.Duration period instead.
- Set the filter only when using SenseContinuous.
- Do not enable automatic sensing upon initialization.
- Use forced mode by default.
=> devices: Add Environmental.SenseContinuous(); implement for bme280 

conn/gpio/gpio_test.go, conn/gpio/gpioreg/gpioreg.go, conn/gpio/gpioreg/gpioreg_test.go, conn/gpio/gpiotest/gpiotest_test.go, devices/tm1637/tm1637_test.go, host/chip/chipsmoketest/chipsmoketest.go, host/odroidc1/odroidc1smoketest/odroidc1smoketest.go
It is still possible to get a pin by its logical number using the string
representation, but the function is not exported anymore.
This simplifies the interface, one less way to do the same thing.
=> gpioreg: Remove ByNumber()

cmd/apa102/main.go, devices/apa102/apa102.go, devices/apa102/apa102_test.go
- Disallow writing a buffer longer than the number used. Silently
dropping data is always annoying to debug. Clear failure is better.
- Rename private variables and document them better.
- Replace 'lights' by 'pixels'. This is more precise.
=> apa102: minor tweaks

conn/gpio/gpiostream/gpiostream.go, conn/gpio/gpiostream/gpiostream_test.go, conn/gpio/gpiostream/gpiostreamtest/gpiostreamtest.go, conn/gpio/gpiostream/gpiostreamtest/gpiostreamtest_test.go
- PinIn only accepts BitStream, as supporting EdgeStream would require
significantly more work and it's not obvious yet this would be valuable.
- Add gpiostreamtest to enable writting unit tests.
=> gpiostream: add PinIn and PinOut, add fakes.

conn/conn.go, devices/apa102/apa102.go, devices/bmxx80/bmxx80.go, devices/devices.go, devices/devicestest/display.go, devices/ds18b20/ds18b20.go, devices/ds248x/dev.go, devices/lepton/cci/cci.go, devices/lepton/cci/cci_test.go, devices/lepton/lepton.go, devices/ssd1306/ssd1306.go, devices/tm1637/tm1637.go, host/sysfs/thermal_sensor.go
In practice I want to be able for gpioreg.Register() to eventually enforce that
Halt() is implemented on gpio.Pin, so that three's a consistent way to stop
gpiostream operations or PWM() output. This requires the interface to live in
conn, not in devices.
Do not use go1.9 type alias to not break compatibility with older Go version
yet.
=> conn: Add Resource, superseds devices.Device

host/bcm283x/bcm283xsmoketest/bcm283xsmoketest.go, host/bcm283x/dma.go, host/bcm283x/gpio.go, host/bcm283x/gpio_test.go
- Uses the native PWM or one of the clock source when possible.
- This will likely be refactored later as full DMA based support is implemented
but this won't change the API itself. Include BUG references as the
implementation is not 100% complete yet, albeit it is safely usable and smoke
tested.
=> bcm283x: activate bcm283x-dma and add Pin.PWM()

host/bcm283x/pwm.go
Fix a problem I described in issue #168.
=> Fix PWM Address Map: add missing paddings.

cmd/periph-smoketest/main.go, host/allwinner/allwinnersmoketest/benchmark.go, host/bcm283x/bcm283xsmoketest/benchmark.go, host/sysfs/sysfssmoketest/benchmark.go
They test the performance of the GPIO for allwinner, bcm283x and sysfs.
Outputs looks like this:
$ ./periph-smoketest bcm283x-benchmark -p 12
Out() 	 3000000	       587 ns/op	1.7Mhz
=> Add smoketest benchmarks

host/bcm283x/gpio.go
- Implement correctly stopping the GPCLK/PWM clock source. This was a known bug.
This also fixes PWM(0, ...) and PWM(gpio.DutyMax, ...) to work as expected.
- Halt() permits to safely stop the clock source, and edge detections.
=> bcm283x.Pin: Improve PWM() and implement conn.Resource

host/bcm283x/gpio.go
Timings for a full cycle (High, Low):
- RPi3:  was 610ns 1.6Mhz, now 460ns, 2.2Mhz (25%)
- RPiZW: was 585ns 1.7Mhz, now 475ns, 2.1Mhz (19%)
It seems that the boundary offset took an unreasonable amount of time compared
to the rest of the execution. Using hard coded offsets in the array with
conditions proved to be significantly faster.
=> bcm283x: boost Pin.Out perf by 25%

host/allwinner/gpio.go
This improves performance on a C.H.I.P. by 10% from 490kHz to 540kHz.
=> allwinner: hardcode groups in Pin.Out()

host/bcm283x/gpio.go
=> bcm283x: Increase read performance up to 13.6MHz

host/bcm283x/bcm283xsmoketest/benchmark.go, host/bcm283x/gpio.go
Paging @simokawa .
I started writing a blog post about it at https://github.com/periph/website/blob/blog_gpio_perf/site/content/news/2017/gpio_perf.md
=> bcm283x: Implement FastOut and corresponding benchmark

host/allwinner/allwinnersmoketest/benchmark.go, host/allwinner/gpio.go, host/allwinner/gpio_pl.go
This raises output performance from 540kHz to 1.8MHz on a C.H.I.P.!
Include many documentation updates, especially for PinPL to reduce the
duplication of documentation, which always leads to a stale copy. :)
=> allwinner: Implement FastOut()

conn/gpio/gpio.go, conn/gpio/gpiotest/gpiotest.go, host/allwinner/gpio.go, host/allwinner/gpio_pl.go, host/bcm283x/gpio.go, host/sysfs/gpio.go, host/sysfs/led.go
- Halt() is going to be necessary for PWM() but it also makes sense to use
Halt() to stop edge detection. It conceptually just make sense for any
continuous operation.
- Changed composite Pin implementation (allwinner and bcm283x) to use an ordered
flow to switch mode: stop edges, switch function, setup pull, setup edges.
- bcm283x: Move Halt() higher so the methods are in the same order than the
other Pin implementations.
The interfaces will be updated in v3 as per issue #183, since this is a breaking
change.
=> gpio: make all Pin implementations implement conn.Resource; fix In()

experimental/cmd/cap1188/main.go, experimental/devices/cap1188/cap1188.go, experimental/devices/cap1188/cap1188_example_test.go, experimental/devices/cap1188/cap1188_options.go, experimental/devices/cap1188/cap1188_test.go
- Make errors consistents.
- Standardize comments.
- Make unit test much faster by not sleeping.
- Reduce the number of properties of Dev.
- Do not export Opts.
- Commented out I/O for unused data.
- Slightly reduce memory usage.
- Comment out NewSPI() since it is not implemented.
=> cap1188: refactor a bit.

host/bcm283x/gpio.go, host/bcm283x/gpio_test.go
These CPU specific functions permits to read or change multiple GPIOs at once.
=> bcm283x: add PinsRead/Clear/Set global functions

host/bcm283x/bcm283xsmoketest/bcm283xsmoketest.go, host/bcm283x/dma.go, host/bcm283x/gpio.go, host/bcm283x/gpio_test.go, host/bcm283x/pwm.go
bcm283x DMA improvements #172
- Enable DMA driven bitstream.
- Start DMA writing PWM FIFO.
- Round off PWM duty.
=> bcm283x: Enable DMA functions.

cmd/bmxx80/main.go, cmd/gpio-list/main.go, cmd/gpio-read/main.go, cmd/gpio-write/main.go, cmd/headers-list/main.go, cmd/i2c-io/main.go, cmd/i2c-list/main.go, cmd/led/main.go, cmd/lepton/main.go, cmd/onewire-list/main.go, cmd/periph-info/main.go, cmd/spi-list/main.go, cmd/thermal/main.go
There's value in having tools in cmd/... all behave similarly. Change flag
processing to be slightly more similar.
=> cmd: make flag processing more coherent

experimental/cmd/mfrc522/main.go, experimental/devices/hd44780/hd44780.go, experimental/devices/mfrc522/mfrc522.go, experimental/devices/mfrc522/mfrc522_test.go
If the passed key is longer than 6 bytes, it will corrupt the access
bits for the traling sector.
Fixed the bit calculation, updates tests.
Changed signatures to accept 6-byte long arrays instead of slices.
Minor typo for HD44780
Signed-off-by: Eugene Dzhurinsky <jdevelop@gmail.com>
=> Fixed MFRC522 trailing sector overflow

experimental/host/beagle/black/black.go
Works on `Linux beaglebone 4.4.113-ti-r147` (official debian-stretch image), however cannot confirm if this works on older versions.
It may make sense to define the values I check as constants or even (assuming this works universally) do this check automatically for different platforms, thus a platform would only have to provide a model string to validate against.
=> updated beagle/black Present() check

devices/lepton/image14bit/gray14.go, devices/lepton/image14bit/gray14_test.go, devices/lepton/image14bit/intensity14.go, devices/lepton/image14bit/intensity14_test.go
This defines a image/draw compatible Gray14 image type and Color14 color type. These will soon be used to store the frames return by the lepton driver.
This is part of the work for #218.
=> lepton: Add new image14bit subpackage

experimental/cmd/cap1188/main.go, experimental/devices/cap1188/cap1188.go, experimental/devices/cap1188/cap1188_options.go, experimental/devices/cap1188/cap1188_test.go, experimental/devices/cap1188/example_test.go
- Change DefaultOpts to be a struct instead of a function. This makes the godoc
much more descriptive.
- Change InputStatus() to accept a slice, so that the driver will be able to
eventually support the flavors cap1155 and cap1166.
=> cap1188: tweaks in the device driver

devices/apa102/apa102_test.go
- Convert existing tests to table-driven
- Make reading []byte diffs easier by aligning lines
- Should be a no-op in terms of what's being tested and with what data
=> apa102: Refactor tests

devices/apa102/apa102_test.go
Should be a no-op.  Benchmark runs look roughly the same as head on my machine.
=> apa102: refactor benchmarks

cmd/apa102/main.go, devices/apa102/apa102.go, devices/apa102/apa102_test.go, devices/apa102/example_test.go
The rationale is that temperature correction can still be used with 8 bits
resolution, but perceptual mapping can't. Tweak the code to enable this, and
make the documentation clearer about the implications.
=> apa102: change from RawColors to DisableGlobalPWM

experimental/devices/bitbang/spi.go
Handles clock-related Mode options for bitbanging SPI.
Fixes #266
=> Implements clock mode handling for bitbang/spi

host/fs/fs.go, host/fs/fs_test.go, host/fs/ioctl_mips_like.go, host/fs/ioctl_other.go
It uses a slightly different linux opcode encoding. Just shuffle the bits as it
goes.
Tested with:
GOARCH=mipsle go build ./...
GOARCH=mips go build ./...
go test ./...
=> fs: add support for GOARCH=mips/mipsle on GOOS=linux

conn/pin/example_test.go, conn/pin/func.go, conn/pin/func_test.go, conn/pin/pin.go, conn/pin/pin_test.go
- This will eventually be implemented by all pin.Pin implementations and merged
back into pin.Pin for v4.
- The pin.Func const in other conn/ packages and host/ implementation is in a
follow up.
=> pin: add PinFunc

host/sysfs/gpio.go
Without this edges are never delivered for me.  *shrug*
=> sysfs-gpio: always reset edge detection to 'none' after starting epoll

experimental/cmd/nrzled/main.go
gpioreg.ByName returns a pinAlias,
which doesn't implement gpiostream.PinOut
=> Use real pin in nrzled

experimental/devices/pca9685/doc.go, experimental/devices/pca9685/example_test.go, experimental/devices/pca9685/pca9685.go, experimental/devices/pca9685/servo.go
Add support for the PCA9685 16 channel PWM module. I create this for a demo on Gophercon Brazil talking about embedded development with Golang and one of the demos was a robot arm (MeArm) controlled through Google Assistant, Cloud IoT Core and Golang running on an Orange Pi Zero. So I extracted the code for controlling the pca9685 module and I'm sending this PR.
Code for the project: https://github.com/alvarowolfx/golang-voice-iot
Demo of it working: https://youtu.be/Xep6dZ3xOYA
Based on https://github.com/wintersandroid/Android-Things-PCA9685
Datasheets: https://cdn-shop.adafruit.com/datasheets/PCA9685.pdf
Product page: https://www.adafruit.com/product/815
=> [feat] Add support for pca9685 pwm module

experimental/devices/ht16k33/alphanum.go, experimental/devices/ht16k33/doc.go, experimental/devices/ht16k33/example_test.go, experimental/devices/ht16k33/ht16k33.go, experimental/devices/rainbowhat/doc.go, experimental/devices/rainbowhat/example_test.go, experimental/devices/rainbowhat/rainbowhat.go
Add support for the Pimoroni's Rainbow HAT with a lot of peripherals. I also created the driver for the HT16K33 that drives the Alphanumeric display on the hat.
Product page: https://shop.pimoroni.com/products/rainbow-hat-for-android-things
=> ht16k33: add support for LED alphanumeric display

experimental/devices/bh1750/bh1750.go, experimental/devices/bh1750/doc.go, experimental/devices/bh1750/example_test.go
Add support to the BH1750 ambient light sensor.
Datasheet: https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT
=> bh1750: Add support for ambient light sensor

experimental/devices/epd/doc.go, experimental/devices/epd/epd.go, experimental/devices/epd/example_test.go
Initial ePaper display support for the Waveshare family of displays. I have the 2.13inch model, that is also a Raspberry Pi Hat. 
Product: https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT
I almost ported from this implementation in Python:
https://github.com/soonuse/epd-library-python
=> epd: add ePaper display support

experimental/cmd/mfrc522/main.go, experimental/devices/mfrc522/commands/low_level.go, experimental/devices/mfrc522/example_test.go, experimental/devices/mfrc522/mfrc522.go
The device itself is not supporting concurrent access. Locking and waiting for a previous operation to finish could introduce a variety of possible dead-locks. While this is not the ideal solution it will prevent hardware-lock for the device if concurrent Read/Write was performed. 
All low-level methods are made private, only 4 left public: 
1. ReadCard
1. ReadAuth
1. WriteCard
1. WriteSectorTrail
I'm not sure whether this is a good approach, tbh, since we're hiding low-level methods which might come in handy sometimes. @jdevelop would be great to have your feedback.
=> mfrc522: make concurrent-safe

experimental/cmd/hx711/main.go, experimental/devices/hx711/hx711.go
HX711 is a 24-bit ADC commonly used for weigh scales.
=> hx711: add experimental driver.

experimental/devices/ads1x15/ads1x15.go, experimental/devices/ads1x15/example_test.go
I fixed some remarks, and added 2 new features:
* Continuous reading
* A flag to indicate if the priority should be on power consumption or conversion quality. That will bias the conversion rate in order to turn the ADC off as long as possible.
=> ads1x15: add continuous reading, add quality bias. Fix min/max values.

experimental/devices/ads1x15/ads1x15.go, experimental/devices/ads1x15/ads1x15_test.go, experimental/devices/ads1x15/doc.go, experimental/devices/ads1x15/example_test.go
- Merge PinForDifferenceOfChannels into PinForChannel.
- Make Channel a type.
- Rename ads1x15AnalogPin to analogPin, it was stuttering.
- Shorten few argument names.
- Remove one memory allocation in analogPin.
- Add a minimalistic unit test.
=> ads1x15: refactor, simplify API

experimental/conn/analog/analog.go, experimental/conn/analog/analog_test.go, experimental/devices/ads1x15/ads1x15.go
Rename the interfaces to be clear about the fact that they represent a single
pin.
Add Reading.
=> analog: improve PinADC and PinDAC

conn/physic/units.go, conn/physic/units_test.go
Brings style improvements from #324 
Minor wording changes in tests.
Changes non exported error name  errerrUnderflowsInt64 to errOverflowsInt64Negative
change dtoi's `mag= -1*mag` to `mag= -mag` and `n= -1*n` to `n= -n` as mentioned in a comment.
=> physic: Bring forward Frequency inline with Electrical Resistance style improvements.

experimental/devices/ads1x15/ads1x15.go, experimental/devices/ads1x15/ads1x15_test.go
I fixed the typo and the lack of mutex when calling Halt() on a pin.
Added unit tests based upon a real device.
Also, I added a convenience String() function on i2ctest.IO, in order to make it easier to write unit tests. Do you think it has value or do you prefer me to remove it?
Last but not least, should I had those devices in the documentation on periph.io? Where is it?
Thanks!
=> ads1x15: fix synchronization

conn/physic/example_test.go, conn/physic/units.go
These are BTU, WattSecond, WattHour and KiloWattHour.
I thought about adding Calorie but because there's so many variances, it's hard
to choose one. The BTU has similar issue but I choose the ISO value.
=> physic: add 4 new Energy constants

experimental/devices/ads1x15/ads1x15.go, experimental/devices/ads1x15/ads1x15_test.go
The issue was that the extra delay introduced in the reading made the ticker tick sometimes faster than the reading could read. So when it was in the select for the 2 channels "stop" vs "tick", it randomly chooses which to process. So, with bad luck, it could go on sending I2C queries.
I checked on a real device and that extra delay was useless.
I also added another I2C transaction just in case there is a slowdown during the test. However, in that case, we're still depending on the order of selection of the select statement, which is random.
=> ads1x15: Fixes #334 - Removed extra delay

conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
Continuation of #303 
Add max/min Distance consts
Add Tests
Add Examples
Add Benchmarks for Distance and ElectricalCurrent Set() for comparison.
```
BenchmarkElectricCurrentSet-4      	10000000	       211 ns/op	       8 B/op	       2 allocs/op
BenchmarkDistanceSet-4				10000000	       176 ns/op	       6 B/op	       2 allocs/op
```
This looks like a bit more complicated, but its not its just unrolled a little with and extra step in the middle for mm and Mm etc, and one at the end for the conversions.
=> physic: Add flag.Value implementation for Distance

conn/physic/units.go, conn/physic/units_test.go
Change decimal type internal representation of digits from []byte to uint64. 
Moves validation of digits to atod from doti.
Update tests for new decimal literal.
Add new test cases to atod().
Update Decimal Benchmarks.
This is a ~2x faster atod() and ~5x faster dtoi(), and helps with #303 remaining units.
=> physic: non exported change: decimal type internal representation.

conn/physic/units.go, conn/physic/units_test.go
Fixes bug in overflow detection in dtoi() when the exponent is large enough that overflow check is passed when it has overflowed and wrapped passed base.
Add fail test case for over overflow.
=> physic: decimal overflow fix.

conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
This is an semi experimental method of maintaining dynamic range of units during conversion from one unit base to another using a lossy decimal multiply algorithm. The results of a decimal multiply can lossless but the maximum guaranteed precision is 18-degrade significant digits, This effectively will always give you at least 9 significant digits. The loss is always in the least significant bits.
As more least significant digits are discarded the processing time increases, with the worst case being roughly equivalent to conversion to float for calculation and back to int64 on amd64. float conversion is about %25 faster in worst case.
This PR helps with #303
=> physic: add flag.Value implementation for Force and Angle

experimental/cmd/pca9548/main.go, experimental/devices/pca9548/doc.go, experimental/devices/pca9548/pca9548.go, experimental/devices/pca9548/pca9548_test.go
Adds initial experimental support a i2c multiplexer. Although only tested with NXP pca9548 it should be compatible with many i2c multiplexers IC's.
=> pca9548: i2c multiplexer

experimental/cmd/mfrc522/main.go, experimental/devices/mfrc522/blockaccess.go, experimental/devices/mfrc522/commands/low_level.go, experimental/devices/mfrc522/example_test.go, experimental/devices/mfrc522/mfrc522.go, experimental/devices/mfrc522/mfrc522_test.go
Fixed the wait for edge block, removed synchronization code.
Moved private-related access methods to the low-level driver.
Added concurrent execution protection via config.
=> mfrc522: reworked public/private API.

conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
This adds support for the flag.Value interface for RelativeHumidity unit type.
Add Set and flag doc examples.
Add Set() for RelativeHumidity.
Add Tests for RelativeHumidity Set().
Add Set() and flag.Value examples for RelativeHumidity.
Helps with #303.
=> physic: Adds flag.Value for RelativeHumidity

conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go
This adds support for the flag.Value interface for Temperature unit type.
Add Set and flag doc examples.
Add Set() for Temperature.
Add Tests for Temperature Set().
Add Set() and flag.Value examples for Temperature.
Fix Fahrenheit rounding error in Example.
Fix Temperature stringer overflow for temperatures > allowed by Celsius.
This should close #303.
=> physic: Adds flag.Value for physic.Temperature

conn/physic/units_test.go
Add tests to check the unit stringer is settable by Set() and are equal to each other.
No external or api change just adds the tests.
=> physic: Set(unit.String()) tests

experimental/cmd/ads1015/main.go
Add a simple cmd to show the use of the ADS1015 AD converter. I added calculation for a voltage divider which is used for example in the automation-hat. The code is taken mainly from the example_test.go but for my development it is useful to have a main.
=> ads1x15: add cmd for ads1015 AD converter with voltage divider calculation

host/sysfs/thermal_sensor.go, host/sysfs/thermal_sensor_test.go
The w1_therm kernel model exposes onewire thermometers under /sys/class/hwmon/
```
$ ls /sys/bus/w1/devices/
28-011319dd865d
28-011319e04763
w1_bus_master1
$ cat /sys/class/hwmon/hwmon*/name 
w1_slave_temp
w1_slave_temp
$ cat /sys/class/hwmon/hwmon*/device/name
28-011319dd865d
28-011319e04763
$ cat /sys/class/hwmon/hwmon*/temp1_input
24250
23750
$ sudo ./thermal
thermal_zone0: cpu_thermal: 36.400°C
hwmon0: 28-011319dd865d: 24.250°C
hwmon1: 28-011319e04763: 23.750°C
```
=> sysfs: include thermal sensors from hwmon

experimental/cmd/mcp9808/main.go, experimental/devices/mcp9808/doc.go, experimental/devices/mcp9808/example_test.go, experimental/devices/mcp9808/mcp9808.go, experimental/devices/mcp9808/mcp9808_test.go, experimental/devices/mcp9808/mcp9808smoketest/mcp9808smoketest.go
Add initial support for microchip i2c MCP9808 temperature sensor.
=> mcp9808: add experimental support for digital temperature sensor

conn/i2c/i2c.go, conn/i2c/i2c_test.go
This is adds a new type i2c.Addr and Set methods that implement the flag.Value interface as a convenience for device maintainers.
Add i2c.Addr
Add i2c.Addr Set()
Add Tests.
helps with #360
=> i2c: Adds i2c.Addr type and flag.Value interface.

host/fs/fs.go, host/fs/fs_linux.go, host/fs/fs_linux_test.go, host/fs/fs_other.go
The new epoll loop has the following properties:
- It uses a single blocking OS thread, independent of the number of
edges watched.
- Notes the timestamp at which each event fires.
Includes unit tests that are testing on OS pipes and sockets, as we
can't assume there's GPIO sysfs handles available (e.g. travis). This
increases code coverage to 70% on linux.
Small doc update to Ioctler.
No externally visible change yet.
=> fs: add new epoll loop to fix issue 323

host/fs/fs_linux.go
Adds syscall.EpollCreate1(0) to use if syscall.EpollCreate(1) fails with "function not implemented."
Should have identical behavior on systems that support syscall.EpollCreate(). Acceptable extra overhead on arm64 to use syscall.EpollCreate1(). If both are not supported the failure behavior is the same as before.
helps with #368
=> host/fs: arm64 EpollCreate

conn/i2c/example_test.go, conn/i2c/i2c.go, conn/i2c/i2c_test.go
Add Addr.String()
Add Flag example
i2c.Addr was missing String() to complete flag.Value interface.
=> i2c: Add Stringer for i2c.Addr

conn/gpio/gpiostream/gpiostream.go, conn/physic/example_test.go, conn/physic/units.go, conn/physic/units_test.go, experimental/conn/gpio/gpioutil/polledge.go, experimental/devices/ads1x15/ads1x15.go, experimental/devices/bitbang/i2c.go, experimental/devices/bitbang/spi.go
- Improve rounding and add unit tests to confirm.
- Period() is the same function than Duration() but better describes what
is returned.
- Fix support for negative value.
- Upgrade all call sites inside periph.
- Fix Frequency documentation that incorrectly stated it's an int32,
it's in fact an int64.
- Duration() will be removed in v4.0.0 as part of issue #379.
=> physic: Improve Frequency rounding, add Period()

conn/physic/units.go, conn/physic/units_test.go
- Make sure that the ones that accept multiple casing work as expected.
Fix Angle.Set(), Distance.Set(), Frequency.Set(), Power.Set() and
Pressure.Set().
- Remove inconsistent support for "pa" in Pressure.Set().
- Add corresponding unit tests.
- Make the test cases more resilient about unexpected success and reuse
more copy-pastable code.
- Make Frequency.Set() allow unitless value to be processed. It makes it
possible to be backward compatible for command line tools.
=> physic: fix inconsistencies in Set() methods; all unitless frequency

cmd/apa102/main.go, cmd/bmxx80/main.go, cmd/cap1xxx/main.go, cmd/i2c-io/main.go, cmd/lepton/main.go, cmd/spi-io/main.go, cmd/ssd1306/main.go, experimental/cmd/nrzled/main.go
This permits the user to specify nicer value like '-hz 1MHz'.
This change is fully backward compatible, as 'naked' frequency is now
supported.
=> cmd: use physic.Frequency as flag.Value

conn/physic/example_test.go
No functional change, just new examples.
=> physic: add examples how to convert to float64

experimental/devices/as7262/as7262.go, experimental/devices/as7262/as7262_test.go
replaces some fragile time based tests with a with cancel context. No external api changes.
=> as7262 add internal context.context

host/sysfs/fs_linux.go, host/sysfs/fs_linux_test.go
It's not used yet. In practice the previous code would have worked
mostly fine, but it's triggering data race check with running tests with
-race, so it's necessary to have this fixed.
=> sysfs: fix a data race condition in events

experimental/devices/mcp9808/mcp9808.go, experimental/devices/mcp9808/mcp9808_test.go
The datasheet (http://ww1.microchip.com/downloads/en/DeviceDoc/25095A.pdf)
says that negative temperatures are stored in two's complement. See
page 22 for alert registers and pages 24-25 for the ambient temperature
register.
However, the code currently assumes negative values are stored in a
sign-and-magnitude representation. Fix this to handle two's complement
values correctly.
For register bits to temperature conversion this implementation follows
the datasheet, but the code in the datasheet isn't quite right -- it
should be `temp - 256` instead of `256 - temp` -- but the fact that the
256 figure is in Microchip's code backs up the idea stated in the text
that negative values are in two's complement. Others seem to agree that
this is correct: …
=> mcp9808: Fix conversions between temperature and bits

experimental/devices/mcp9808/mcp9808.go, experimental/devices/mcp9808/mcp9808_test.go
Converting the alert registers and the ambient temp register to a
physic.Temperature can use the same procedure. Unify them and document
why this is possible.
=> mcp9808: Simplify bits to temperature conversions

experimental/host/netlink/doc.go, experimental/host/netlink/netlink_linux.go, experimental/host/netlink/netlink_other.go, experimental/host/netlink/onewire.go
This driver adds a gpio-based 1-wire master that uses the Linux netlink
connector API to communicate with the w1 kernel module.
Major caveat: the w1 netlink API does not support setting strong
pull-ups after write operations. Devices such as the DS18B20 must be
powered externally in order to work with this driver.
Fixes #359
=> onewire: experimental netlink-based bus master for Linux

experimental/cmd/inky/inky.go, experimental/devices/inky/inky.go
* Use maxTxSize from conn.Limits
* Show an error instead of crashing on invalid pin names
=> inky: Minor cleanups

host/bcm283x/gpio.go
This is required to use periph.io on https://gokrazy.org.
I don’t know whether the device-tree method also works on Raspbian. If so, would you like to use just the device-tree method everywhere, or do you want to go the more conservative fall-back approach I’m suggesting here?
Thanks,
=> bcm283x: present: check device tree on non-raspbian systems

host/distro/devtree.go, host/rpi/rpi.go
This is required to use periph.io on https://gokrazy.org.
This change was tested on:
Raspbian (2020-02-13-raspbian-buster-lite.img)
Raspberry Pi 4 Model B Rev 1.1
Raspberry Pi 3 Model B Rev 1.2
gokrazy (Linux 5.6.2)
Raspberry Pi 4 Model B Rev 1.1
Raspberry Pi 3 Model B Rev 1.2
=> rpi: obtain revision from device tree (for non-raspbian systems)

experimental/devices/pca9685/pca9685.go, experimental/devices/pca9685/pca9685_test.go, experimental/devices/pca9685/pins.go
Provide PWM functionality of PCA9685 via gpio Pin API.
=> pca9685: added gpio pin API

experimental/devices/epd/image2bit/image2bit.go, experimental/devices/epd/image2bit/image2bit_test.go
Add image format with two bit planes as used by some waveshare e-Paper
devices.
Helps with implementing gray scale on these e-Paper devices, but needs a driver too.
=> epd/image2bit: e-paper 2 bit gray scale bit plane image format

experimental/devices/pca9685/pca9685.go, experimental/devices/pca9685/pca9685_test.go, experimental/devices/pca9685/pins.go
This change incorporates two improvements for the pca9685 driver.
* My previous contribution included a bug, it scaled the duty cycle to 16 bits instead of the 12 bit resolution of this device.
* Now the full-off/full-on bits can be used as shortcuts to 0% and 100% duty with slightly less I2C traffic.
=> pca9685: Added Full-on/off support, fixed scaling to 12 bits

devices/ssd1306/ssd1306.go, devices/ssd1306/ssd1306_test.go
I changed ssd1306 driver to write page-by-page, and made column differential work without corrupting screen. This change is also preparation for sh1106 support, which I have working locally and plan to contribute in the future.
=> ssd1306: Made column differential work for SSD1306

experimental/host/netlink/onewire.go
When responding to a sequence of 1-wire commands, the kernel driver
individually acks every single one. It is important to keep reading all
of these messages in case of an error in order to flush the netlink
socket for future commands.
=> netlink/onewire: fix error handling when reading from the netlink socket

devices/cap1xxx/cap1xxx.go
When dealing with a CAP1166 device (6 LEDs, 6 touch sensors), the touch sensors input statuses were not detected correctly.
The index referred by the byte shifting if was `7`, probably referring to the 8 touch sensors of the CAP1188.
Moving that index from  the original `7` to `len(d.inputStatuses) - 1` helped detect all of the input statuses from a Pimoroni Touch-Phat device.
=> cap1xxx.go: shift touch sensors input statuses by d.inputStatuses array len

experimental/cmd/st7567/main.go, experimental/devices/st7567/doc.go, experimental/devices/st7567/example_test.go, experimental/devices/st7567/st7567.go
This adds experimental support for the st7567 LCD device which is used by the GFX HAT from Pimoroni. 
The example just places some pixels on the device and iterates over the possible contrast values, going into power save mode and waking up.
The command line tool can take a PNG image and paints the black pixels onto the LCD. 
Example and command line tool have been tested with a GFX Hat.
=> st7567: add experimental device driver for 128x64 dot matrix LCD

experimental/devices/st7567/st7567.go
Hi,
two minor cleanups for the experimental st7567 device
* Fixes a comment for the CommonDirection
* Do not allocate unnecessary nulls for byte array
=> experimental st7567: Minor cleanup

host/pine64/pine64.go
Read the model name from /proc/device-tree/model (via distro.DTModel())
instead of probing for /boot/pine64.dtb to be present.
There's various distros out there that don't have a /boot/pine64.dtb,
and /proc/device-tree/model is a much nicer way to do this.
=> host/pine64: improve detection
